# Generated by Django 2.2.6 on 2020-11-15 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import hya_main.customfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Postava',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vytvoreno', models.DateTimeField(blank=True, null=True)),
                ('jmeno', models.CharField(max_length=30, null=True, verbose_name='Křestní jméno')),
                ('prijmeni', models.CharField(max_length=50, null=True, verbose_name='Příjmení')),
                ('narozeni', models.DateField(null=True, verbose_name='Datum narození')),
                ('narodnost', models.CharField(default='Česká', max_length=20, verbose_name='Národnost')),
                ('vyska', models.IntegerField(default=180, null=True, verbose_name='Výška')),
                ('nabozenstvi', models.CharField(max_length=20, null=True, verbose_name='Vyznání')),
                ('politika', models.CharField(max_length=20, null=True, verbose_name='Politická orientace')),
                ('vzdelani', models.CharField(max_length=50, null=True, verbose_name='Vzdělání')),
                ('rodice', models.CharField(max_length=70, null=True, verbose_name='Rodiče')),
                ('jazyky', models.CharField(max_length=70, null=True, verbose_name='Jazyky')),
                ('hobby', models.CharField(max_length=50, null=True, verbose_name='Koníčky')),
                ('bio', models.TextField(null=True, verbose_name='Životopis')),
                ('cele_jmeno', models.CharField(max_length=81, null=True)),
                ('majitel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Postavy',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('urltitle', models.CharField(max_length=50, null=True)),
                ('tags', hya_main.customfields.TagField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('content', models.TextField(null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Clanek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulek', models.CharField(max_length=100)),
                ('obsah', models.TextField()),
                ('vytvoreno', models.DateTimeField(default=django.utils.timezone.now)),
                ('publikovano', models.DateTimeField(blank=True, null=True)),
                ('kategorie', models.IntegerField(choices=[(1, 'Bazoš'), (2, 'BloxNews'), (3, 'InstaBlox'), (4, 'Internet'), (5, 'Úřední deska')], default=1)),
                ('obrazek', models.FileField(null=True, upload_to='obrazky/')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('postava', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hya_main.Postava', verbose_name='Postava jako autor')),
            ],
            options={
                'verbose_name_plural': 'Clanky',
            },
        ),
    ]
