# Generated by Django 2.2.13 on 2021-01-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hya_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanek',
            name='slug',
            field=models.SlugField(default='testovaci-clanek'),
            preserve_default=False,
        ),
    ]
